### PR TITLE
Adding deeplearning4j to the supported libraries

### PR DESCRIPTION
**Pull request by fbrunacci**
Hi,

Here is a pull request to add deeplearning4j to the list of supported libraries.
I had to make two libraries so that the loading of cuda can be done correctly.
I also add some samples.

With regards.
Fabien Brunacci

### CODE REVIEW

**Comment by altavir** [comment]
There are quite a lot of questions in slack about using dl4j in kotlin. It would be really good to have a couple of basic examples in a separate repository/gist/article.

**Comment by fbrunacci** [comment]
I have just start a repository [here](https://github.com/fbrunacci/kotlin-notebook-samples) to test and train myself at deeplearning. 

Even if I am not sure I can answer it, I will take a look at these questions. How can I take a look at it?
Do you have types of examples in mind.

**Comment by altavir** [comment]
@fbrunacci Nice. You are welcome to join kotlin slack at http://kotl.in/slack and go to #datascience channel (or general #science). The most common question is "how can I do machine learning in kotlin". Sadly it is just the most general one.

**Comment by ileasile** [comment]
@fbrunacci Please, rebase your branch onto current master

**Pull request closed without merging**
